//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FINALLEntities1 : DbContext
    {
        public FINALLEntities1()
            : base("name=FINALLEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArriveNote> ArriveNotes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PendingNote> PendingNotes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
    }
}
