//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINALL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatu
    {
        public string RqID { get; set; }
        public string CID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Payment { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PendingNote PendingNote { get; set; }
        public virtual Product Product { get; set; }
    }
}
